<?php

/**
 * Implementation of hook_menu().
 */
function ting_search_autocomplete_menu() {
  $items = array();

  $items['ting/autocomplete'] = array(
    'title'            => 'Ting search autocomplete',
    'description'      => 'Returns a list of suggestions to use for autocompletion',
    'access arguments' => array('search content'),
    'page callback'    => 'ting_search_autocomplete',
    'type'             => MENU_CALLBACK,
    'file'             => 'ting_search_autocomplete.pages.inc',
  );

  return $items;
}

/**
 * Implementation of hook_flush_caches().
 */
function ting_search_autocomplete_flush_caches() {
  return array('cache_ting_search_autocomplete');
}

/**
 * Implements hook_form_alter() for the ting_search_autocomplete form.
 */
function ting_search_autocomplete_form_search_block_form_alter(&$form, &$form_state) {
  $scan_url = variable_get('ting_scan_url', '');
  $spell_url = variable_get('ting_spell_url', '');

  drupal_add_library('system', 'ui.autocomplete');
  drupal_add_css(drupal_get_path('module', 'ting_search_autocomplete') . '/css/ting_search_autocomplete.css');
  drupal_add_js(drupal_get_path('module', 'ting_search_autocomplete') . '/js/ting_search_autocomplete.js');

  $js_setting = array(
    'ting_search_autocomplete' => array(
      'autocomplete_enabled' => FALSE
    ),
  );

  if (!empty($scan_url) && !empty($spell_url)) {
    $js_setting['ting_search_autocomplete']['autocomplete_enabled'] = TRUE;
  }

  drupal_add_js($js_setting, 'setting');
}

